package dao;

import java.sql.Connection;
import java.sql.SQLException;

import dao.mapper.IMapResultSetToEntity;
import dao.repository.IEnumerationValueRepository;
import dao.uow.IUnitOfWork;
import domain.EnumerationValue;

public class EnumerationValueRepository extends Repository<EnumerationValue> implements IEnumerationValueRepository{

	public EnumerationValueRepository(IUnitOfWork uow, IMapResultSetToEntity<EnumerationValue> mapper,
			Connection connection) {
		super(uow, mapper, connection);
		
	}

	public void withName(String name) {
		// TODO Auto-generated method stub
		
	}

	public void withIntKey(int key, String name) {
		// TODO Auto-generated method stub
		
	}

	public void withStringKey(String key, String name) {
		// TODO Auto-generated method stub
		
	}

	@Override
	protected String getTableName() {
		
		return "enumerationValue";
	}

	@Override
	protected String insertSql() {
		return "INSERT INTO enumerationValue(intKey,stringKey,value,enumerationName) VALUES (?,?,?,?)";	
	}

	@Override
	protected String updateSql() {
		return "UPDATE enumerationValue SET (intKey,stringKey,value,enumerationName)=(?,?,?,?) WHERE id=?";
	}

	@Override
	protected String createTableSql() {
		return "CREATE TABLE enumerationValue("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
				+ "intKey int," + "stringKey VARCHAR(50)," + "value int,"+ "enumerationName VARCHAR(50),"
				+ ")";
	}

	@Override
	protected void setUpdate(EnumerationValue entity) throws SQLException {
		update.setInt(1, entity.getIntKey());
		update.setString(2, entity.getStringKey());
		update.setInt(3, entity.getValue());
		update.setString(4, entity.getEnumerationName());
		
	}

	@Override
	protected void setInsert(EnumerationValue entity) throws SQLException {
		insert.setInt(1, entity.getIntKey());
		insert.setString(2, entity.getStringKey());
		insert.setInt(3, entity.getValue());
		insert.setString(4, entity.getEnumerationName());
	}

}
